spring:
  application:
    name: readnext
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.6-sol
google:
  books:
    url: https://www.googleapis.com/books/v1/volumes
    api-key: ${GOOGLE_BOOKS_API_KEY}
